
const bondDatas = [
  {
    key: '1',
    name: 'DFS-USDT',
    status: 'opened',
    from: '/images/dfs.png',
    to: '/images/bond/usdt.png',
    price: '0',
    discount: 0,
    duration: '',
    balance: 0,
    maxFee: '0',
    getFee: '0',
  },
  {
    key: '2',
    name: 'DFS-BNB',
    status: 'closed',
    from: '/images/dfs.png',
    to: '/images/bnb.png',
    price: '0',
    discount: 0,
    duration: '',
    balance: 0,
    maxFee: '0',
    getFee: '0',
  },
  {
    key: '3',
    name: 'DFS-ETH',
    status: 'closed',
    from: '/images/dfs.png',
    to: '/images/bond/eth.png',
    price: '0',
    discount: 0,
    duration: '',
    balance: 0,
    maxFee: '0',
    getFee: '0',
  },
  {
    key: '4',
    name: 'DFS-AVAX',
    status: 'closed',
    from: '/images/dfs.png',
    to: '/images/bond/avax.png',
    price: '0',
    discount: 0,
    duration: '',
    balance: 0,
    maxFee: '0',
    getFee: '0',
  },
  {
    key: '5',
    name: 'DFS-FTM',
    status: 'closed',
    from: '/images/dfs.png',
    to: '/images/bond/ftm.png',
    price: '0',
    discount: 0,
    duration: '',
    balance: 0,
    maxFee: '0',
    getFee: '0',
  },
]

export default bondDatas
